# Creating a NumPy Array

In [1]:
import numpy as np 
list1= [0,1,2,3,4]
arr = np.array(list1)

print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[0 1 2 3 4]


In [2]:
import numpy as np 
list1
list = list1+2

TypeError: can only concatenate list (not "int") to list

In [ ]:
import numpy as np 
list1 = [0,1,2,3,4]
arr = np.array(list1)
print(arr)
arr = arr+2
print(arr)

[0 1 2 3 4]
[2 3 4 5 6]


In [ ]:
import numpy as np
list2 = [[0,1,2],[3,4,5],[6,7,8]]
arr2 = np.array(list2)
print(arr2)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
import numpy as np 
list2 = [[0,1,2],[3,4,5],[6,7,8]]
arr2 = np.array(list2)
print(arr2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
import numpy as np
list2 = [[0,1,2],[3,4,5],[6,7,8]]
arr3 = np.array(list2, dtype = 'float')
print(arr3)


[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [ ]:
import numpy as np
list2 = [[0,1,2],[3,4,5],[6,7,8]]
print(arr3)
arr3_s = arr3.astype('int').astype('str')
print(arr3_s)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[['0' '1' '2']
 ['3' '4' '5']
 ['6' '7' '8']]


In [ ]:
arr_obj = np.array([1,'a'], dtype = 'object')
print(arr_obj)

[1 'a']


In [ ]:
arr_list = arr_obj.tolist()
print(arr_list)

[1, 'a']


In [ ]:
arr_list = arr_obj.tolist()
print(arr_list)

[1, 'a']


In [ ]:
import numpy as np
list2 = [[0,1,2],[3,4,5],[6,7,8]]
arr3 = np.array(list2, dtype = 'float')
print("Shape: ", arr3.shape)
print("Data type: ", arr3.dtype)
print("Size: ", arr3.size)
print("Num dimensions: ", arr3.ndim)   

Shape:  (3, 3)
Data type:  float64
Size:  9
Num dimensions:  2


In [ ]:
import numpy as np
list2 = [[0,1,2],[3,4,5],[6,7,8]]
arr3 = np.array(list2, dtype = 'float')
print("Whole: ", arr3)
print("Part: ", arr3[:2, :2])


Whole:  [[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
Part:  [[0. 1.]
 [3. 4.]]


In [ ]:
import numpy as np
list2 = [[0,1,2],[3,4,5],[6,7,8]]
arr3 = np.array(list2, dtype = 'float')
boo = arr3>2
print(boo)

[[False False False]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
import pandas as pd 
new_series = pd.Series([5,6,7,8,9,10])
print(new_series)

0     5
1     6
2     7
3     8
4     9
5    10
dtype: int64


In [ ]:
import pandas as pd 
new_series = pd.Series([5,6,7,8,9,10])
print(new_series.values)
print('__________________')
print(new_series[4])

[ 5  6  7  8  9 10]
__________________
9


In [ ]:
import pandas as pd
new_series = pd.Series([5,6,7,8,9,10], index = ['a','b','c','d','e','f'])
print(new_series.values)
print('__________________')
print(new_series['f'])

[ 5  6  7  8  9 10]
__________________
10


In [ ]:
import pandas as pd 
new_series = pd.Series([5,6,7,8,9,10], index = ['a','b','c','d','e','f'])
print(new_series)
print('__________________')
new_series[['a','b','f']] = 0
print(new_series)

a     5
b     6
c     7
d     8
e     9
f    10
dtype: int64
__________________
a    0
b    0
c    7
d    8
e    9
f    0
dtype: int64


In [ ]:
import pandas as pd
new_series = pd.Series([5,6,7,8,9,10], index = ['a','b','c','d','e','f'])
new_series2 = new_series[new_series>0]
print(new_series2)
print('__________________')
new_series2[new_series2>0]*2
print(new_series2)
print('__________________')
new_series2[new_series2>0]*2
print(new_series2)

a     5
b     6
c     7
d     8
e     9
f    10
dtype: int64
__________________
a     5
b     6
c     7
d     8
e     9
f    10
dtype: int64
__________________
a     5
b     6
c     7
d     8
e     9
f    10
dtype: int64


In [ ]:
import pandas as pd
df = pd.DataFrame({
    'country': ['Kazakhstan', 'Russia', 'Belarus', 'Ukraine'],
    'population': [17.04, 143.5, 9.5, 45.5],
    'square': [2724902, 17125191, 207600, 603628]
})
print(df)

      country  population    square
0  Kazakhstan       17.04   2724902
1      Russia      143.50  17125191
2     Belarus        9.50    207600
3     Ukraine       45.50    603628


In [ ]:
import pandas as pd 
list2 = [[0,1,2],[3,4,5],[6,7,8]]
df = pd.DataFrame(list2)
print(df)
df.columns = ['V1', 'V2', 'V3']
print(df)

   0  1  2
0  0  1  2
1  3  4  5
2  6  7  8
   V1  V2  V3
0   0   1   2
1   3   4   5
2   6   7   8


In [ ]:
print(type(df['country']))

<class 'pandas.core.series.Series'>


In [ ]:
import pandas as pd
df = pd.DataFrame({
    'country': ['Kazakhstan', 'Russia', 'Belarus', 'Ukraine'],
    'population': [17.04, 143.5, 9.5, 45.5],
    'square': [2724902, 17125191, 207600, 603628]
})
print(df.columns)
print('__________________')
print(df.index)

Index(['country', 'population', 'square'], dtype='object')
__________________
RangeIndex(start=0, stop=4, step=1)


In [ ]:
import pandas as pd
df = pd.DataFrame({
    'country': ['Kazakhstan', 'Russia', 'Belarus', 'Ukraine'],
    'population': [17.04, 143.5, 9.5, 45.5],
    'square': [2724902, 17125191, 207600, 603628]
}, index = ['KZ', 'RU', 'BY', 'UA'])
print(df)

       country  population    square
KZ  Kazakhstan       17.04   2724902
RU      Russia      143.50  17125191
BY     Belarus        9.50    207600
UA     Ukraine       45.50    603628


In [ ]:
import pandas as pd
df = pd.DataFrame({
    'country': ['Kazakhstan', 'Russia', 'Belarus', 'Ukraine'],
    'population': [17.04, 143.5, 9.5, 45.5],
    'square': [2724902, 17125191, 207600, 603628]
})
print(df)
print('__________________')
df.index = ['KZ', 'RU', 'BY', 'UA']
df.index.name = 'Country Code'
print(df)


      country  population    square
0  Kazakhstan       17.04   2724902
1      Russia      143.50  17125191
2     Belarus        9.50    207600
3     Ukraine       45.50    603628
__________________
                 country  population    square
Country Code                                  
KZ            Kazakhstan       17.04   2724902
RU                Russia      143.50  17125191
BY               Belarus        9.50    207600
UA               Ukraine       45.50    603628


In [ ]:
print(df.loc['KZ'])

country       Kazakhstan
population         17.04
square           2724902
Name: KZ, dtype: object


In [ ]:
print(df.iloc[0])

country       Kazakhstan
population         17.04
square           2724902
Name: KZ, dtype: object


In [ ]:
print(df.loc[['KZ', 'RU'], 'population'])

Country Code
KZ     17.04
RU    143.50
Name: population, dtype: float64


In [ ]:
print(df.loc['KZ':'BY', :])

                 country  population    square
Country Code                                  
KZ            Kazakhstan       17.04   2724902
RU                Russia      143.50  17125191
BY               Belarus        9.50    207600


In [ ]:
print(df[df.population > 10][['country', 'square']])

                 country    square
Country Code                      
KZ            Kazakhstan   2724902
RU                Russia  17125191
UA               Ukraine    603628
