# Python Exercise: Introduction to NumPy and Pandas

### Import 

In [1]:
import numpy as np
import pandas as pd

## Part 1

#### Task 1: Creating the array 

In [2]:
array1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

**Make the array into numpy array**

In [3]:
array1 = np.array(array1)

#### Task 2: Reshapnig the array 

In [4]:
array2 = np.reshape(array1, (3, 5))

In [5]:
print(array2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


#### Task 3: Create a new array

In [6]:
array3 = array2 + 2 
print(array3)

[[ 3  4  5  6  7]
 [ 8  9 10 11 12]
 [13 14 15 16 17]]


#### Task 4: Extract the second row

In [7]:
ndRow = array2[1]
print(ndRow)

[ 6  7  8  9 10]


#### Task 5: Multiply each element

In [8]:
array4 = array2 * 3

#### Task 6: Calculate the mean and sum

In [9]:
print(np.mean(array4))

24.0


In [10]:
print(np.sum(array4))

360


## Part 2 

#### Task 7: Creating DataFrames

In [11]:
data = {
    'Name': ['Tom', 'Jane', 'Steve'],
    'Age': [28, 34, 29],
    'Salary': [50000, 60000, 55000]
}

In [12]:
df = pd.DataFrame(data)
df

Name  Age  Salary
0    Tom   28   50000
1   Jane   34   60000
2  Steve   29   55000

#### Task 8: Accessing DataFrame Columns

In [13]:
df['Name']

0      Tom
1     Jane
2    Steve
Name: Name, dtype: object

#### Task 9: Adding a New Column

In [14]:
df['Bonus'] = df['Salary'] * 0.12
df['Bonus']

0    6000.0
1    7200.0
2    6600.0
Name: Bonus, dtype: float64

#### Task 10: Basic DataFrame Statistics

In [15]:
print(df['Salary'].mean())

55000.0


In [16]:
df

Name  Age  Salary   Bonus
0    Tom   28   50000  6000.0
1   Jane   34   60000  7200.0
2  Steve   29   55000  6600.0